Controllers/RoleController.cs
using IdentityManager.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace IdentityManager.Controllers
{
    [Route("role")]
    [Authorize]
    public class RoleController : BaseController
    {
        private readonly ILogger<UserController> _logger;
        private readonly ApplicationDbContext _db;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController
        (
            ILogger<UserController> logger,
            ApplicationDbContext db,
            RoleManager<IdentityRole> roleManager
        )
        {
            _logger = logger;
            _db = db;
            _roleManager = roleManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var roles = _db.Roles.ToList();
            return View(roles);
        }

        [HttpGet("upsert")]
        public IActionResult Upsert(string roleId=null)
        {
            if(String.IsNullOrEmpty(roleId))
            {
                return View();
            }
            else
            {
                var role = _db.Roles.FirstOrDefault(r => r.Id == roleId);
                if(role==null)
                {
                    TempData["error"] = "Role not found!";
                    return RedirectToAction(nameof(Index));
                }
                return View(role);
            }
        }

        [HttpPost("upsert")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(IdentityRole role, string roleId=null)
        {
            if(String.IsNullOrEmpty(role.Id))
            {
                await _roleManager.CreateAsync(new IdentityRole
                {
                    Name = role.Name,
                    NormalizedName = role.Name.ToUpper()
                }
                );
                TempData["success"] = "Role created successfully!";
            }
            else
            {
                var _role = await _roleManager.FindByIdAsync(roleId);
                if(_role == null)
                {
                    TempData["error"] = "Role not found!";
                    return RedirectToAction(nameof(Index));
                }
                _role.Name = role.Name;
                _role.NormalizedName = role.Name!.ToUpper();
                var result = await _roleManager.UpdateAsync(_role);
                TempData["success"] = "Role updated successfully!";
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost("delete")]
        public async Task<IActionResult> Delete([FromQuery]string roleId)
        {
            var role = _db.Roles.FirstOrDefault(r => r.Id == roleId);
            if(role==null)
                return NotFound("Role not found!");

            var userRolesFirThisRole = _db.UserRoles.Count(ur => ur.RoleId == roleId);
            if( userRolesFirThisRole > 0 )
            {
                TempData["error"] = "Role cannot be deleted!";
                return RedirectToAction(nameof(Index));
            }

            await _roleManager.DeleteAsync(role);
            TempData["success"] = "Role deleted successfully!";
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/UserController.cs
using IdentityManager.Data;
using IdentityManager.Models;
using IdentityManager.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace IdentityManager.Controllers
{
    [Route("user")]
    [Authorize]
    public class UserController : BaseController
    {
        private readonly ILogger<UserController> _logger;
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserController
        (
            ILogger<UserController> logger,
            ApplicationDbContext db,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager
        )
        {
            _logger = logger;
            _db = db;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userList = _db.ApplicationUser.ToList();
            var userRole = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();

            foreach(var user in userList)
            {
                user.Role = await _userManager.GetRolesAsync(user) as List<string>;
            }

            return View(userList);
        }

        [HttpGet("manage-role")]
        public async Task<IActionResult> ManageRole([FromQuery]string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound();
            }

            List<string>? existingUserRoles = await _userManager.GetRolesAsync(user) as List<string>;
            var model = new RolesViewModel()
            {
                User = user
            };
            foreach (var role in _roleManager.Roles)
            {
                RoleSelection roleSelection = new RoleSelection()
                {
                    RoleName = role.Name
                };
                if (existingUserRoles.Any(c => c == role.Name))
                {
                    roleSelection.IsSelected = true;
                }
                model.RolesList.Add(roleSelection);
            }
            return View(model);
        }

        [HttpPost("manage-role")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageRole(RolesViewModel model, [FromQuery]string userId)
        {
            var user = await _userManager.FindByIdAsync(model.User.Id);
            if (user == null)
            {
                return NotFound();
            }
            if(user.Id != model.User.Id)
            {
                return BadRequest();
            }
            
            var oldUserRoles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, oldUserRoles);
            if (!result.Succeeded)
            {
                TempData["error"] = "Error removing existing roles";
                return View(model);
            }

            result = await _userManager.AddToRolesAsync(
                user,
                model.RolesList.Where(x => x.IsSelected).Select(y => y.RoleName)
            );
            if (!result.Succeeded)
            {
                TempData["error"] = "Error adding new roles";
                return View(model);
            }
            TempData["success"] = "Roles updated successfully";
            return RedirectToAction(nameof(Index));
        }

        [HttpPost("lock-unlock-user")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LockUnlockUser([FromQuery]string userId)
        {
            var user = await _db.ApplicationUser.FirstOrDefaultAsync(c => c.Id == userId);
            if (user == null)
            {
                return NotFound();
            }
            
            if(user.LockoutEnd != null && user.LockoutEnd > DateTime.Now)
            {
                user.LockoutEnd = DateTime.Now;
                TempData["success"] = "User unlocked successfully";
            }
            else
            {
                user.LockoutEnd = DateTime.Now.AddYears(100);
                TempData["success"] = "User locked successfully";
            }
            await _db.SaveChangesAsync();
            
            return RedirectToAction(nameof(Index));
        }
        
        [HttpPost("delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromQuery]string userId)
        {
            var user = _db.ApplicationUser.FirstOrDefault(c => c.Id == userId);
            if (user == null)
            {
                return NotFound();
            }

            _db.ApplicationUser.Remove(user);
            await _db.SaveChangesAsync();
            
            TempData["success"] = "User deleted successfully";
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_AuthenticationLinkPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityManager.Models.ApplicationUser> SignInManager
@inject UserManager<IdentityManager.Models.ApplicationUser> UserManager

<ul class="navbar-nav">

  @if(SignInManager.IsSignedIn(User))
  {
    <li class="nav-item">
      <a class="nav-link" href="#">Hello @UserManager.GetUserName(User)</a>
    </li>
    <li class="nav-item">
      <form method="post" asp-controller="Account" asp-action="Logout">
        <button type="submit" class="btn nav-link">Logout</button>
      </form>
    </li>
  }
  else
  {
    <li class="nav-item">
      <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
    </li>
  }
</ul>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IdentityManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css"/>
    <link rel="stylesheet" href="~/IdentityManager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IdentityManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>
                    </ul>
                    <partial name="_AuthenticationLinkPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - IdentityManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <partial name="_Notifications" />
</body>
</html>

Views/Shared/_Notifications.cshtml
@if (TempData["success"]!=null)
{
    <script>
        $(document).ready(function(){
            toastr.success('@TempData["success"]');
        });
    </script>
}
@if (TempData["error"]!=null)
{
    <script>
        $(document).ready(function(){
            toastr.error('@TempData["error"]');
        });
    </script>
}